"""A generated file says what regenerates it, and carries no timestamp.

Enforces `DEP-007` (a provenance header), `DEP-008` (no timestamp in generated
output) and `DOC-012` (rendered documentation is not committed).

`DEP-008` is the one that looks pedantic and is not. A timestamp makes every
regeneration produce different bytes, so `--check` can never mean "this is
current" -- it means "this was rebuilt just now". Every drift check downstream of
that is then decorative, and the corpus's own byte-stability guarantee, which is
what `build_index --check` and `build_graph --check` rest on, cannot hold at all.

**How a generated file is recognised.** By its own claim. A file announcing that
it is generated is held to the other two rules; a file making no such claim is
not examined, because nothing in a syntax tree can tell a written table from a
rendered one.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

from . import Finding, TextCheck, main

if TYPE_CHECKING:
    from collections.abc import Iterator
    from pathlib import Path

## How far into a file a provenance banner may sit. Beyond this it is prose about
## generation rather than a header announcing it.
HEADER_LINES = 12

## A file claiming to be generated. The capitalised forms are matched
## case-sensitively on purpose: a lowercase "generated file" is what a rule module
## *about* generation carries in its own router keywords, and `law/DEP.md` was
## reported as generated output on this check's first run for exactly that.
_CLAIMS = re.compile(r"(GENERATED\b|DO NOT EDIT|[Aa]uto-?generated|generated by tools)")

## Evidence that the claim names what to re-run: a script path or a command.
_NAMES_GENERATOR = re.compile(r"([\w./-]+\.py\b|python\s+[\w./-]+|`[^`]+`)")

## A stamp of when the file was *made*, which is what breaks byte-stability.
##
## A bare date is deliberately not one. A generated file may legitimately carry
## dates that are data -- a `verified:` date quoted from a source, a calibration
## run's `--as-of` parameter -- and those reproduce identically on every run,
## which is the property `DEP-008` actually protects. Reporting them flagged three
## correct files here before this was narrowed. What is reported is a clock
## reading, or a date introduced as the moment of generation.
_TIMESTAMP = re.compile(
    r"(\b\d{2}:\d{2}:\d{2}\b"
    r"|(?:generated|built|rendered|created|updated)\s+(?:on|at)\s+"
    r"\S{0,12}(?:\b(19|20)\d{2}[-/]\d{2}[-/]\d{2}\b|\b\d{2}:\d{2}\b))",
    re.IGNORECASE,
)

## Path segments that name a documentation build tree. Anything scanned from one
## of these is rendered output that should never have been committed.
BUILD_DIRS = frozenset({"_build", "site"})


class GeneratedProvenanceCheck(TextCheck):
    """Reports a generated file with no generator named, or with a timestamp."""

    ## Invoked as `python -m checks.generated_provenance`.
    name = "generated_provenance"
    ## The law/DEP and law/DOC rules this check decides.
    rules = ("DEP-007", "DEP-008", "DOC-012")
    ## Generated output is markdown, JSON or TOML far more often than Python.
    suffixes = (".md", ".json", ".toml", ".yaml", ".yml", ".html")

    def visit_text(self, text: str, path: Path) -> Iterator[Finding]:
        """Yield findings for a generated file's provenance and its timestamps.

        @param text the file's contents
        @param path the file it was read from
        @return one finding per defect
        """
        if _is_rendered_documentation(path):
            yield Finding(
                "DOC-012", path, 1,
                "rendered documentation is present in the tree",
                "The reviewable artefact is the comment in the source. A large "
                "rendered tree in every diff is how reviewers are trained to wave "
                "generated output through.",
            )
            return

        lines = text.splitlines()
        header = "\n".join(lines[:HEADER_LINES])
        if not _CLAIMS.search(header):
            return

        if not _NAMES_GENERATOR.search(header):
            yield Finding(
                "DEP-007", path, 1,
                "the file says it is generated but does not say by what",
                "Name the command that regenerates it. A reader who cannot "
                "regenerate a file will eventually edit it instead.",
            )

        for number, line in enumerate(lines, start=1):
            found = _TIMESTAMP.search(line)
            if found is None:
                continue
            yield Finding(
                "DEP-008", path, number,
                f"generated output carries the timestamp {found.group(0)!r}",
                "Remove it. A timestamp makes every regeneration produce "
                "different bytes, so a staleness check can never mean 'this is "
                "current' -- only 'this was rebuilt just now'.",
            )
            return


def _is_rendered_documentation(path: Path) -> bool:
    """Whether a path sits inside a documentation build tree.

    @param path the file being examined
    @return True when a build-output directory is on its path
    """
    parts = set(path.parts)
    if parts & BUILD_DIRS:
        return True
    return "build" in parts and "doc" in parts


if __name__ == "__main__":
    raise SystemExit(main(GeneratedProvenanceCheck()))
