"""Regenerate the corpus's derived artifacts.

    python tools/build_index.py [--check] [--root PATH]

Writes four things, none of which may be edited by hand:

* the measured ``tokens:`` field in every module's front-matter, so an agent can
  budget before it reads;
* ``discipline/INDEX.md``   -- one line per rule, for scanning;
* ``discipline/rules.json`` -- the same data for ``grep`` and ``jq``;
* ``enforce/ENFORCEMENT.md`` -- every rule against the mechanism that decides it,
  plus the unenforceable surface, so the axiom's cost is visible.

``--check`` writes nothing and exits non-zero if anything is stale, which is the
form to run in CI.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Final

from discipline_core import (
    REPO_ROOT,
    Document,
    Enforcement,
    Force,
    Kind,
    ParseError,
    Rule,
    count_tokens,
    enforcement_of,
    mechanism_is_implemented,
    parse_document,
)

if TYPE_CHECKING:
    from collections.abc import Sequence

## Heads every generated Markdown file this tool writes, so a human who opens one is
## warned before spending an edit that the next rebuild will overwrite.
GENERATED_BANNER: Final = (
    "<!-- GENERATED by tools/build_index.py -- do not edit; "
    "change the source module and rebuild. -->"
)
## The only line this tool edits inside a hand-written module; everything else it
## produces is a whole file it owns and overwrites.
_TOKENS_LINE = re.compile(r"^tokens:\s*\d+\s*$", re.MULTILINE)


@dataclass(frozen=True, slots=True)
class Artifact:
    """One generated file and the text it should contain."""

    ## Where the file belongs, absolute.
    path: Path
    ## Its full intended contents, trailing newline included.
    text: str

    def is_stale(self) -> bool:
        """Whether what is on disk differs from what was just computed.

        A file that does not exist counts as stale, so a fresh checkout reports
        work to do rather than agreement.

        @return True when writing would change the tree
        """
        if not self.path.exists():
            return True
        return self.path.read_text(encoding="utf-8") != self.text

    def write(self) -> None:
        """Put the text on disk, creating any parent directory it needs.

        Unconditional. Staleness is the caller's question; this leaves the file
        in the intended state either way.
        """
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(self.text, encoding="utf-8")


def load(root: Path) -> list[Document]:
    """Parse every corpus document, reporting a bad file instead of raising on it.

    One unparsable module must not block the rebuild of the other artifacts; it
    is named on stderr and its rules are simply absent from the output, which is
    visible in the counts the run prints.

    @param root the repository root
    @return the documents that parsed, in path order
    """
    documents: list[Document] = []
    for path in sorted((root / "discipline").rglob("*.md")):
        if path.name in {"INDEX.md"}:
            continue
        try:
            documents.append(parse_document(path))
        except ParseError as exc:
            print(f"skipping unparsable {path}: {exc.reason}", file=sys.stderr)
    return documents


def refresh_tokens(documents: Sequence[Document], *, write: bool) -> list[Path]:
    """Bring each module's declared ``tokens:`` back to what the file measures.

    Writing the number changes the file's length and so its own count, which is
    why the substitution is iterated rather than applied once. A drift of two
    tokens or less is left alone, so a rebuild does not churn the whole corpus
    over rounding.

    @param documents the parsed corpus
    @param write False to measure only, touching nothing
    @return the modules whose declared count was wrong, whether or not it was fixed
    """
    stale: list[Path] = []
    for doc in documents:
        text = doc.path.read_text(encoding="utf-8")
        measured = count_tokens(text)
        declared = doc.front_matter.get("tokens")
        # Rewriting changes length, so converge rather than assume one pass.
        if isinstance(declared, int) and abs(declared - measured) <= 2:
            continue
        stale.append(doc.path)
        if not write:
            continue
        updated = text
        for _ in range(4):
            candidate = _TOKENS_LINE.sub(
                f"tokens: {count_tokens(updated)}", updated, count=1
            )
            if candidate == updated:
                break
            updated = candidate
        doc.path.write_text(updated, encoding="utf-8")
    return stale


## Each `auto:` tool the corpus names, against whether THIS repository's own gate
## runs it. `external` means "a configured tool settles it", and until gate steps
## 7 and 8 existed that status was being read as though the tool ran -- for four
## of these it ran nowhere at all. The distinction is worth printing because it
## is the difference between a rule that is decided and one that is merely
## delegated.
##
## The value is either the gate entry that runs the tool, or the reason it is not
## run here. `_external_tool_section` cross-checks the former against
## `tools/gate.py::GATE`, so a claim that a step exists cannot outlive the step.
EXTERNAL_TOOLS: Final[dict[str, str]] = {
    "ruff": "format and lint",
    "import-linter": "import contracts",
    "mypy": "types",
    "pyright": "types",
    "mutmut": "NOT RUN -- mutmut 3.3.1 does an unconditional `import resource` at "
              "module scope, and `resource` is Unix-only. It raises "
              "ModuleNotFoundError on Windows before parsing an argument, so it "
              "cannot be pinned or wired here. TEST-013 is delegated and undecided.",
}


def _external_tool_section() -> list[str]:
    """The table of external tools against the gate step that runs each.

    @return the rendered lines
    @throws ValueError when a tool claims a gate entry that `GATE` does not carry,
        which would make this table a claim rather than a reading
    """
    import gate  # ruff: ignore[import-outside-top-level] - a sibling in tools/

    entries = {name for name, _ in gate.GATE}
    unknown = [
        f"{tool} -> {where}" for tool, where in EXTERNAL_TOOLS.items()
        if not where.startswith("NOT RUN") and where not in entries
    ]
    if unknown:
        message = f"EXTERNAL_TOOLS names gate entries that do not exist: {'; '.join(unknown)}"
        raise ValueError(message)

    lines = [
        "## External mechanisms, and whether this repository runs them",
        "",
        ("`external` says a configured tool decides the rule. It does not say the "
         "tool ever runs. Four of the rows below were `external` while their tool "
         "ran nowhere in this tree, which is indistinguishable from unenforced."),
        "",
        "| Tool | Run by this repository's gate |",
        "|---|---|",
    ]
    for tool, where in sorted(EXTERNAL_TOOLS.items()):
        cell = where if where.startswith("NOT RUN") else f"yes -- gate step `{where}`"
        lines.append(f"| `{tool}` | {cell} |")
    lines.append("")
    return lines


def _sorted_rules(documents: Sequence[Document]) -> list[Rule]:
    """Every rule in the corpus, ordered by prefix then ordinal.

    One order shared by all three artifacts, so a diff of any of them tracks the
    corpus rather than the order the files happened to be read in.

    @param documents the parsed corpus
    @return the rules, flattened out of the modules that own them
    """
    return sorted(
        (rule for doc in documents for rule in doc.rules),
        key=lambda r: (r.prefix, r.ordinal),
    )


def statuses_for(rules: Sequence[Rule], root: Path) -> dict[str, Enforcement]:
    """Measure every rule's enforcement status against the tree as it stands.

    One pass shared by all three artifacts, so `INDEX.md`, `rules.json` and
    `ENFORCEMENT.md` can never disagree about which rules are actually decided --
    the disagreement being the whole reason the measurement is centralised in
    `discipline_core` rather than reimplemented per artifact.

    @param rules the corpus rules, in any order
    @param root the repository root the mechanisms are resolved against
    @return each rule id against its status
    """
    return {rule.rule_id: enforcement_of(rule.mechanisms, root) for rule in rules}


def _status_cell(rule: Rule, status: Enforcement) -> str:
    """Render one rule's status for a table, loud when the tag overstates it.

    The vocabulary word is always present so the column stays greppable; the
    marker is added only for the case a reader must not skim past -- a rule that
    reads as binding and that nothing decides.

    @param rule the rule the status belongs to, read for its force tag
    @param status the measured status
    @return the cell text
    """
    if rule.force is Force.BINDING and not status.is_mechanical:
        return f"`{status}` **(!)**"
    return f"`{status}`"


def build_index(documents: Sequence[Document], root: Path) -> Artifact:
    """Render `discipline/INDEX.md`: a module catalogue, then one row per rule.

    This is what an agent greps when it does not yet know which module owns a
    thing, so each module row carries the size and the first six of its trigger
    keywords -- enough to decide against opening it, and truncated because the
    row has to stay scannable. Meta documents are left out of the catalogue: they
    describe the corpus rather than govern code.

    Each rule row carries its measured enforcement status beside its force tag,
    because the two are different facts and a reader given only the tag will read
    it as a guarantee. The count of rules that are binding and not mechanised is
    stated at the top rather than left to be summed from the tables.

    @param documents the parsed corpus
    @param root the repository root, fixing both the destination and the links
    @return the intended path and contents; nothing is written
    """
    rules = _sorted_rules(documents)
    status = statuses_for(rules, root)
    overstated = sum(
        1 for r in rules
        if r.force is Force.BINDING and not status[r.rule_id].is_mechanical
    )
    by_module: defaultdict[str, list[Rule]] = defaultdict(list)
    for rule in rules:
        by_module[rule.module_id].append(rule)

    lines = [
        "---",
        "id: meta/INDEX",
        "kind: meta",
        "title: Rule Index",
        "tokens: 0",
        "decay: none",
        "---",
        "",
        GENERATED_BANNER,
        "",
        "# Rule Index",
        "",
        f"{len(rules)} rules across {len(by_module)} modules. "
        "Grep this file for a rule id, then open only the module that owns it.",
        "",
        "**Force is a claim; Status is a measurement.** `Force` is what the rule's "
        "heading declares. `Status` is what this tree was found to contain when the "
        "index was built: `mechanized` -- every named mechanism was found here; "
        "`external` -- nothing is missing but a configured tool or a reviewer settles "
        "it; `review` -- a person decides it, and no gate will ever report it; "
        "`unbuilt` -- a named check or fitness function does not exist; "
        "`unmechanized` -- the rule names no mechanism at all. A row marked **(!)** "
        "is binding and mechanically undecided: treat it as an obligation, not as "
        "something the gate will catch for you.",
        "",
        (
            "**`mechanized` says a mechanism exists, not that it decides the whole "
            "rule.** The measurement is presence on disk; how completely a check covers "
            "the sentence above it is a judgement no build can make. `ARCH-012` is the "
            "worked example: `check:no_test_branches` is real and runs, and it matches a "
            'closed list of test signals, so `if os.environ.get("PYTEST_CURRENT_TEST")` '
            "-- the canonical pytest detector -- passes it, as does any indirection "
            "through a module constant. Read a `mechanized` row as *something will catch "
            "the obvious cases*, and the rule's own text as what you actually owe."
        ),
        "",
        f"{overstated} of {sum(1 for r in rules if r.force is Force.BINDING)} binding "
        "rules are not mechanically decided. `enforce/ENFORCEMENT.md` names the "
        "mechanisms still to build.",
        "",
    ]

    catalogue = sorted(
        (d for d in documents if d.kind in {Kind.LAW, Kind.FACT, Kind.FRAME, Kind.OPS}),
        key=lambda d: (str(d.kind), d.doc_id),
    )
    if catalogue:
        lines += ["## Modules", "", "| Module | Kind | Tokens | Rules | Load when |", "|---|---|---|---|---|"]
        for doc in catalogue:
            keywords = doc.front_matter.get("load_when")
            hint = ", ".join(str(k) for k in keywords[:6]) if isinstance(keywords, list) else ""
            lines.append(
                f"| [{doc.doc_id}]({_link(doc, root)}) | {doc.kind} | "
                f"{doc.front_matter.get('tokens', 0)} | {len(doc.rules)} | {hint} |"
            )
        lines.append("")

    if rules:
        lines += ["## Rules", ""]
        for module_id, module_rules in sorted(by_module.items()):
            lines += [
                f"### {module_id}",
                "",
                "| Rule | Force | Status | Mechanism | Title |",
                "|---|---|---|---|---|",
            ]
            for rule in module_rules:
                mechanisms = " ".join(f"`{m}`" for m in rule.mechanisms) or "—"
                lines.append(
                    f"| `{rule.rule_id}` | {rule.force} | "
                    f"{_status_cell(rule, status[rule.rule_id])} | "
                    f"{mechanisms} | {rule.title} |"
                )
            lines.append("")

    return Artifact(root / "discipline" / "INDEX.md", "\n".join(lines).rstrip() + "\n")


def _link(doc: Document, root: Path) -> str:
    """A Markdown href to a module, written from where `INDEX.md` will sit.

    @param doc the module to point at
    @param root the repository root
    @return the path relative to `discipline/`, the directory INDEX.md is
        generated into
    @throws ValueError when the module lies outside `discipline/`, which would
        mean it was never part of the corpus this index describes
    """
    return doc.path.relative_to(root / "discipline").as_posix()


def build_rules_json(documents: Sequence[Document], root: Path) -> Artifact:
    """Render `discipline/rules.json`: the same corpus, shaped for a query.

    Carries every field a rule declares, including the ones INDEX.md has no
    column for -- the statement, the reasoning, the supersession -- so that a
    question can be answered without falling back to reading the module. Each
    rule keeps its file and line, which is what makes an answer citable.

    Each rule also carries `enforcement`, measured rather than declared: it says
    whether the mechanisms the heading names were actually found in this tree.
    `mechanisms` is what the author wrote; `enforcement` is what is there. A
    consumer asking "is this rule enforced" must read the second, and a rule that
    is `BINDING` with an `enforcement` other than `mechanized` or `external` is
    binding in name only.

    @param documents the parsed corpus
    @param root the repository root, for the relative paths in the payload
    @return the intended path and contents; nothing is written
    """
    status = statuses_for(_sorted_rules(documents), root)
    payload = {
        "generated_by": "tools/build_index.py",
        "modules": [
            {
                "id": doc.doc_id,
                "kind": str(doc.kind) if doc.kind else None,
                "title": doc.front_matter.get("title"),
                "tokens": doc.front_matter.get("tokens"),
                "load_when": doc.front_matter.get("load_when", []),
                "requires": doc.front_matter.get("requires", []),
                "grounds_on": doc.front_matter.get("grounds_on", []),
                "verified": str(doc.front_matter.get("verified"))
                if doc.front_matter.get("verified")
                else None,
                "decay": doc.front_matter.get("decay"),
                "path": doc.path.relative_to(root).as_posix(),
            }
            for doc in sorted(documents, key=lambda d: d.doc_id)
            if doc.doc_id
        ],
        "rules": [
            {
                "id": rule.rule_id,
                "module": rule.module_id,
                "title": rule.title,
                "force": str(rule.force),
                "mechanisms": list(rule.mechanisms),
                "enforcement": str(status[rule.rule_id]),
                "mechanically_enforced": status[rule.rule_id].is_mechanical,
                "statement": rule.statement,
                "why": rule.why,
                "check": rule.check,
                "no_mechanism": rule.no_mechanism,
                "see": list(rule.see),
                "superseded_by": rule.superseded_by,
                "path": rule.path.relative_to(root).as_posix(),
                "line": rule.line,
            }
            for rule in _sorted_rules(documents)
        ],
    }
    return Artifact(
        root / "discipline" / "rules.json",
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
    )


def build_enforcement(documents: Sequence[Document], root: Path) -> Artifact:
    """Render `enforce/ENFORCEMENT.md`, where the axiom's cost is made visible.

    A binding rule counts as enforced only when some machine decides it -- every
    named mechanism resolving to something on disk, or to a configured tool's own
    rule. A rule naming none counts as unenforced, and so does one whose only
    mechanism is `review`: judgment is a mechanism in the corpus's grammar but it
    is not one that fails a gate, and counting it as enforced would overstate the
    very number this file exists to keep honest. A mechanism that does not exist is
    listed by name in its own table instead of being quietly totalled as built. The
    advisory section is the admitted unenforceable surface, and an entry there with
    no stated reason is printed as unjustified.

    @param documents the parsed corpus
    @param root the repository root, fixing the destination and locating mechanisms
    @return the intended path and contents; nothing is written
    """
    rules = _sorted_rules(documents)
    status = statuses_for(rules, root)
    binding = [r for r in rules if r.force is Force.BINDING]
    advisory = [r for r in rules if r.force is Force.ADVISORY]
    open_rules = [r for r in rules if r.force is Force.OPEN]
    named = {m for r in rules for m in r.mechanisms}
    pending = sorted(m for m in named if mechanism_is_implemented(m, root) is False)
    built = len(named) - len(pending)
    enforced = sum(1 for r in binding if status[r.rule_id].is_mechanical)
    overstated = [r for r in binding if not status[r.rule_id].is_mechanical]
    share = f"{enforced / len(binding):.0%}" if binding else "n/a"
    census = Counter(str(status[r.rule_id]) for r in rules)

    lines = [
        GENERATED_BANNER,
        "",
        "# Enforcement",
        "",
        "Every rule against the mechanism that decides it. The corpus's own standard is "
        "that a rule nothing checks is not binding in practice, whatever its tag says, so "
        "this table is where that claim is either kept or exposed.",
        "",
        f"- **{len(binding)}** binding rules; **{enforced}** are decided by something "
        f"that runs ({share}). The other **{len(overstated)}** read as binding and are "
        "not mechanically decided.",
        f"- **{len(advisory)}** advisory rules -- the unenforceable surface, listed below with reasons.",
        f"- **{len(open_rules)}** rules blocked on an open decision.",
        f"- **{built}/{len(named)}** named mechanisms are built; **{len(pending)}** are "
        "declared but not yet implemented.",
        "",
        "## Status census",
        "",
        "Measured against this tree, not declared. `discipline/rules.json` carries the "
        "same value per rule as `enforcement`, and `discipline/INDEX.md` shows it in the "
        "`Status` column.",
        "",
        "| Status | Rules | Means |",
        "|---|---|---|",
        f"| `mechanized` | {census['mechanized']} | every named mechanism was found here |",
        f"| `external` | {census['external']} | nothing missing, but a configured tool or "
        "a reviewer settles it |",
        f"| `review` | {census['review']} | a person decides it; no gate will report it |",
        f"| `unbuilt` | {census['unbuilt']} | a named check or fitness function does not exist |",
        f"| `unmechanized` | {census['unmechanized']} | the rule names no mechanism at all |",
        "",
    ]

    lines += _external_tool_section()

    if overstated:
        lines += [
            "## Binding but not mechanically decided",
            "",
            "These read as obligations a gate will catch, and no gate will. Until the "
            "mechanism exists, each is enforced only by whoever remembers it.",
            "",
            "| Rule | Status | Mechanism | Title |",
            "|---|---|---|---|",
        ]
        for rule in overstated:
            mechanisms = " ".join(f"`{m}`" for m in rule.mechanisms) or "—"
            lines.append(
                f"| `{rule.rule_id}` | `{status[rule.rule_id]}` | {mechanisms} | {rule.title} |"
            )
        lines.append("")

    if pending:
        lines += [
            "> **Mechanisms still to build.** Listed rather than assumed closed: a rule "
            "whose mechanism does not exist is binding in name only. `tools/validate.py` "
            "reports each as `V080`.",
            "",
            "| Mechanism | Rules |",
            "|---|---|",
        ]
        for mechanism in pending:
            owners = ", ".join(
                f"`{r.rule_id}`" for r in rules if mechanism in r.mechanisms
            )
            lines.append(f"| `{mechanism}` | {owners} |")
        lines.append("")

    if binding:
        lines += [
            "## Binding",
            "",
            "| Rule | Status | Mechanism | Check | Title |",
            "|---|---|---|---|---|",
        ]
        for rule in binding:
            mechanisms = " ".join(f"`{m}`" for m in rule.mechanisms) or "—"
            lines.append(
                f"| `{rule.rule_id}` | {_status_cell(rule, status[rule.rule_id])} | "
                f"{mechanisms} | {rule.check or '—'} | {rule.title} |"
            )
        lines.append("")

        counts = Counter(m.split(":", 1)[0] for r in binding for m in r.mechanisms)
        lines += ["### Mechanisms in use", "", "| Kind | Rules |", "|---|---|"]
        lines += [f"| `{kind}` | {n} |" for kind, n in sorted(counts.items())]
        lines.append("")

    if advisory:
        lines += [
            "## Advisory -- the unenforceable surface",
            "",
            "Each of these was tried against a mechanism and could not be reduced to one. "
            "Drive this list toward zero; an entry that has become checkable should be "
            "retagged rather than left here.",
            "",
            "| Rule | Why no mechanism exists | Title |",
            "|---|---|---|",
        ]
        for rule in advisory:
            lines.append(
                f"| `{rule.rule_id}` | {rule.no_mechanism or '**unjustified**'} | {rule.title} |"
            )
        lines.append("")

    if open_rules:
        lines += [
            "## Blocked on an open decision",
            "",
            "| Rule | Title |",
            "|---|---|",
        ]
        lines += [f"| `{r.rule_id}` | {r.title} |" for r in open_rules]
        lines.append("")

    return Artifact(root / "enforce" / "ENFORCEMENT.md", "\n".join(lines).rstrip() + "\n")


def main(argv: Sequence[str] | None = None) -> int:
    """Regenerate every derived artifact, or under `--check` only report staleness.

    Rewriting the token counts changes the very files the artifacts describe, so
    the corpus is parsed a second time whenever a count actually moved, and the
    artifacts then carry the new numbers rather than the ones measured before the
    pass. Under `--check` nothing is rewritten, so nothing is re-read.

    @param argv command-line arguments, defaulting to `sys.argv`
    @return 0 on success, 1 when `--check` finds anything out of date
    """
    # The console encoding is not ours to choose, and a tool that dies on one is
    # worse than one that renders a character imperfectly.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser(description="Regenerate derived corpus artifacts.")
    parser.add_argument("--check", action="store_true", help="report staleness, write nothing")
    parser.add_argument("--root", type=Path, default=REPO_ROOT, help="repository root")
    args = parser.parse_args(argv)
    root = args.root.resolve()

    documents = load(root)
    stale_tokens = refresh_tokens(documents, write=not args.check)
    if stale_tokens and not args.check:
        documents = load(root)  # re-read so the artifacts carry the new counts

    artifacts = [
        build_index(documents, root),
        build_rules_json(documents, root),
        build_enforcement(documents, root),
    ]
    stale = [a for a in artifacts if a.is_stale()]

    if args.check:
        for path in stale_tokens:
            print(f"stale tokens: {path.relative_to(root).as_posix()}")
        for artifact in stale:
            print(f"stale artifact: {artifact.path.relative_to(root).as_posix()}")
        total = len(stale_tokens) + len(stale)
        print(f"{total} stale file(s)." if total else "up to date.")
        return 1 if total else 0

    for artifact in artifacts:
        artifact.write()
    rules = sum(len(d.rules) for d in documents)
    print(
        f"wrote {len(artifacts)} artifact(s); {len(documents)} modules, {rules} rules, "
        f"{len(stale_tokens)} token count(s) refreshed."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
