"""Regenerate the corpus's derived artifacts.

    python tools/build_index.py [--check] [--root PATH]

Writes four things, none of which may be edited by hand:

* the measured ``tokens:`` field in every module's front-matter, so an agent can
  budget before it reads;
* ``discipline/INDEX.md``   -- one line per rule, for scanning;
* ``discipline/rules.json`` -- the same data for ``grep`` and ``jq``;
* ``enforce/ENFORCEMENT.md`` -- every rule against its distinct normative,
  decidable, discrimination, portability, residual, and field-evidence claims.

``--check`` writes nothing and exits non-zero if anything is stale, which is the
form to run in CI.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Final

from discipline_core import (
    REPO_ROOT,
    Document,
    Force,
    Kind,
    ParseError,
    Rule,
    count_tokens,
    mechanism_is_implemented,
    parse_document,
)
from evidence_model import (
    DecisionRelation,
    EvidenceRegistry,
    ObservationRegistry,
    RuleEvidence,
    VerificationState,
    discrimination_covered,
    load_evidence,
    load_observations,
    verification_state,
)

if TYPE_CHECKING:
    from collections.abc import Sequence

## Heads every generated Markdown file this tool writes, so a human who opens one is
## warned before spending an edit that the next rebuild will overwrite.
GENERATED_BANNER: Final = (
    "<!-- GENERATED by tools/build_index.py -- do not edit; "
    "change the source module and rebuild. -->"
)
## The only line this tool edits inside a hand-written module; everything else it
## produces is a whole file it owns and overwrites.
_TOKENS_LINE = re.compile(r"^tokens:\s*\d+\s*$", re.MULTILINE)
## Token estimates are deliberately approximate; rewriting for tiny tokenizer
## variation would churn every generated artifact without changing load choices.
_TOKEN_DRIFT: Final = 2
## Shared wide table headings kept out of renderer literals so the Python source
## remains readable while the generated Markdown remains one physical row.
_INDEX_RULE_HEADER: Final = (
    "| Rule | Force | Verifier | Relation | Rejection | Platforms | Residual | Field | Title |"
)
## Same evidence dimensions in the detailed ledger's preferred column order.
_LEDGER_RULE_HEADER: Final = (
    "| Rule | Force | Verifier | Relation | Rejection | Platforms | Field | Residual | Title |"
)


@dataclass(frozen=True, slots=True)
class Artifact:
    """One generated file and the text it should contain."""

    ## Where the file belongs, absolute.
    path: Path
    ## Its full intended contents, trailing newline included.
    text: str

    def is_stale(self) -> bool:
        """Whether what is on disk differs from what was just computed.

        A file that does not exist counts as stale, so a fresh checkout reports
        work to do rather than agreement.

        @return True when writing would change the tree
        """
        if not self.path.exists():
            return True
        return self.path.read_text(encoding="utf-8") != self.text

    def write(self) -> None:
        """Put the text on disk, creating any parent directory it needs.

        Unconditional. Staleness is the caller's question; this leaves the file
        in the intended state either way.
        """
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(self.text, encoding="utf-8", newline="\n")


@dataclass(frozen=True, slots=True)
class EvidenceCensus:
    """The aggregate facts rendered above the per-rule evidence table."""

    ## Rules grouped by normative force.
    binding: tuple[Rule, ...]
    ## Advisory rules retained for the rationale section.
    advisory: tuple[Rule, ...]
    ## Open rules retained for the blocked-decision section.
    open_rules: tuple[Rule, ...]
    ## Declared mechanism tags and the local subset that cannot be resolved.
    named_mechanisms: frozenset[str]
    ## Local mechanism tags whose implementation cannot be resolved.
    pending_mechanisms: tuple[str, ...]
    ## Binding rules whose declared strategy is missing or not built.
    unavailable: tuple[Rule, ...]
    ## VerificationState value against number of rules in that state.
    state_counts: Counter[str]
    ## Strategy relation and evidence totals.
    strategy_count: int
    ## Strategies whose proposition directly decides their stated claim.
    direct_count: int
    ## Strategies whose proposition leaves a broader semantic claim unresolved.
    proxy_count: int
    ## Rules carrying at least one machine-executed strategy.
    automated_rule_count: int
    ## Automated rules credited by the inherited rule-keyed mutation matrix.
    witnessed_rule_count: int
    ## Rules connected to one or more named adopter observations.
    observed_rule_count: int


def load(root: Path) -> list[Document]:
    """Parse every corpus document, reporting a bad file instead of raising on it.

    One unparsable module must not block the rebuild of the other artifacts; it
    is named on stderr and its rules are simply absent from the output, which is
    visible in the counts the run prints.

    @param root the repository root
    @return the documents that parsed, in path order
    """
    documents: list[Document] = []
    for path in sorted((root / "discipline").rglob("*.md")):
        if path.name == "INDEX.md":
            continue
        try:
            documents.append(parse_document(path))
        except ParseError as exc:
            print(f"skipping unparsable {path}: {exc.reason}", file=sys.stderr)
    return documents


def refresh_tokens(documents: Sequence[Document], *, write: bool) -> list[Path]:
    """Bring each module's declared ``tokens:`` back to what the file measures.

    Writing the number changes the file's length and so its own count, which is
    why the substitution is iterated rather than applied once. A drift of two
    tokens or less is left alone, so a rebuild does not churn the whole corpus
    over rounding.

    @param documents the parsed corpus
    @param write False to measure only, touching nothing
    @return the modules whose declared count was wrong, whether or not it was fixed
    """
    stale: list[Path] = []
    for doc in documents:
        text = doc.path.read_text(encoding="utf-8")
        measured = count_tokens(text)
        declared = doc.front_matter.get("tokens")
        # Rewriting changes length, so converge rather than assume one pass.
        if isinstance(declared, int) and abs(declared - measured) <= _TOKEN_DRIFT:
            continue
        stale.append(doc.path)
        if not write:
            continue
        updated = text
        for _ in range(4):
            candidate = _TOKENS_LINE.sub(f"tokens: {count_tokens(updated)}", updated, count=1)
            if candidate == updated:
                break
            updated = candidate
        doc.path.write_text(updated, encoding="utf-8", newline="\n")
    return stale


## Each `auto:` tool the corpus names, against whether THIS repository's own gate
## runs it. `external` means "a configured tool settles it", and until gate steps
## 7 and 8 existed that status was being read as though the tool ran -- for four
## of these it ran nowhere at all. The distinction is worth printing because it
## is the difference between a rule that is decided and one that is merely
## delegated.
##
## The value is either the gate entry that runs the tool, or the reason it is not
## run here. `_external_tool_section` cross-checks the former against
## `tools/gate.py::GATE`, so a claim that a step exists cannot outlive the step.
EXTERNAL_TOOLS: Final[dict[str, str]] = {
    "ruff": "format and lint",
    "import-linter": "import contracts",
    "mypy": "types",
    "pyright": "types",
    "cosmic-ray": "PROJECT GATE -- `mutation`; the adapter independently rejects "
    "zero mutants, survivors, abnormal workers, and Cosmic Ray's `incompetent` outcome.",
}


def _external_tool_section() -> list[str]:
    """Render external tool strategies against their repository integration.

    @return the rendered lines
    @throws ValueError when a tool claims a gate entry that `GATE` does not carry,
        which would make this table a claim rather than a reading
    """
    import gate  # ruff: ignore[import-outside-top-level] - a sibling in tools/

    entries = {name for name, _ in gate.GATE}
    unknown = [
        f"{tool} -> {where}"
        for tool, where in EXTERNAL_TOOLS.items()
        if not where.startswith(("NOT RUN", "PROJECT GATE")) and where not in entries
    ]
    if unknown:
        message = f"EXTERNAL_TOOLS names gate entries that do not exist: {'; '.join(unknown)}"
        raise ValueError(message)

    lines = [
        "## External tool integration",
        "",
        (
            "An `external-verifier` state says the strategy delegates a proposition to "
            "a tool. This independent table says whether this repository's gate actually "
            "invokes that tool; availability and an executed pass remain different facts."
        ),
        "",
        "| Tool | Run by this repository's gate |",
        "|---|---|",
    ]
    for tool, where in sorted(EXTERNAL_TOOLS.items()):
        cell = (
            where
            if where.startswith(("NOT RUN", "PROJECT GATE"))
            else f"yes -- gate step `{where}`"
        )
        lines.append(f"| `{tool}` | {cell} |")
    lines.append("")
    return lines


def _sorted_rules(documents: Sequence[Document]) -> list[Rule]:
    """Every rule in the corpus, ordered by prefix then ordinal.

    One order shared by all three artifacts, so a diff of any of them tracks the
    corpus rather than the order the files happened to be read in.

    @param documents the parsed corpus
    @return the rules, flattened out of the modules that own them
    """
    return sorted(
        (rule for doc in documents for rule in doc.rules),
        key=lambda r: (r.prefix, r.ordinal),
    )


def registry_for(root: Path) -> EvidenceRegistry:
    """Load the authored evidence registry belonging to one corpus.

    @param root repository whose generated views are being built
    @return structurally validated evidence records
    """
    return load_evidence(root / "discipline" / "meta" / "evidence.json")


def observations_for(root: Path) -> ObservationRegistry:
    """Load the authored field observations belonging to one corpus.

    @param root repository whose generated views are being built
    @return structurally validated observation records
    """
    return load_observations(root / "discipline" / "meta" / "observations.json")


def statuses_for(
    rules: Sequence[Rule], root: Path, registry: EvidenceRegistry
) -> dict[str, VerificationState]:
    """Describe verifier availability without reporting an unexecuted outcome.

    One pass shared by all generated views prevents one artifact from calling a
    strategy available while another calls it absent. A state never means that
    the strategy passed; only the project gate can report that runtime fact.

    @param rules corpus rules, in any order
    @param root repository the local mechanism paths are resolved against
    @param registry evidence joined to every stable rule id
    @return each rule id against its verifier-availability state
    """
    return {
        rule.rule_id: verification_state(rule, registry.rules[rule.rule_id], root) for rule in rules
    }


def _status_cell(rule: Rule, status: VerificationState) -> str:
    """Render one verifier state, marking absent strategies on binding rules.

    @param rule normative rule the state belongs to
    @param status verifier availability, never an execution result
    @return greppable state with a loud marker only for absence or missing code
    """
    if rule.force is Force.BINDING and status in {
        VerificationState.UNBUILT,
        VerificationState.UNDECLARED,
    }:
        return f"`{status}` **(!)**"
    return f"`{status}`"


def _relations(evidence: RuleEvidence) -> str:
    """Render the direct/proxy relations represented by a rule's strategies.

    @param evidence authored strategies for one rule
    @return distinct relation labels, or not-applicable when there are no strategies
    """
    relations = sorted({str(strategy.relation) for strategy in evidence.strategies})
    return ", ".join(f"`{relation}`" for relation in relations) or "n/a"


def _platforms(evidence: RuleEvidence) -> str:
    """Render the declared supported-platform union for a rule.

    @param evidence authored strategies for one rule
    @return distinct supported platform labels
    """
    platforms = sorted({
        platform for strategy in evidence.strategies for platform in strategy.platforms
    })
    return ", ".join(f"`{platform}`" for platform in platforms) or "n/a"


def _discrimination(rule: Rule, evidence: RuleEvidence, covered: frozenset[str] | None) -> str:
    """Render the evidence actually earned by the current mutation matrix.

    The v3 matrix is keyed by rule, so it can witness that at least one strategy
    rejected a case but cannot identify which strategy did so. The wording keeps
    that coarse evidence distinct from the proposition-level matrix v4 requires.

    @param rule normative rule whose id keys the inherited matrix
    @param evidence strategies that determine whether rejection is required
    @param covered rule ids loaded from the inherited matrix, or None if absent
    @return precise label for the available discrimination evidence
    """
    automated = [strategy for strategy in evidence.strategies if strategy.is_automated]
    if not automated:
        return "n/a"
    if covered is None:
        return "`unknown`"
    if rule.rule_id in covered:
        return "`rule-level witnessed`"
    return "`pending`"


def _residual(evidence: RuleEvidence, *, limit: int = 96) -> str:
    """Render a compact but substantive residual for the scanning index.

    @param evidence authored strategies carrying residual claims
    @param limit maximum rendered characters before an ellipsis
    @return escaped residual text suitable for a Markdown table cell
    """
    residuals = [strategy.residual.replace("|", "\\|") for strategy in evidence.strategies]
    if not residuals:
        return "n/a"
    text = "; ".join(residuals)
    if len(text) <= limit:
        return text
    return f"{text[: limit - 1].rstrip()}…"


def _observations(evidence: RuleEvidence) -> str:
    """Render field-evidence IDs without turning their count into a quality score.

    @param evidence authored observation links
    @return observation identifiers or an explicit absence
    """
    return ", ".join(f"`{item}`" for item in evidence.observations) or "none"


def build_index(documents: Sequence[Document], root: Path) -> Artifact:
    """Render `discipline/INDEX.md`: a module catalogue, then one row per rule.

    This is what an agent greps when it does not yet know which module owns a
    thing, so each module row carries the size and the first six of its trigger
    keywords -- enough to decide against opening it, and truncated because the
    row has to stay scannable. Meta documents are left out of the catalogue: they
    describe the corpus rather than govern code.

    Each rule row keeps normative force, verifier availability, claim relation,
    witnessed rejection, portability, residual, and field evidence in distinct
    columns. None of those facts is allowed to stand in for another.

    @param documents the parsed corpus
    @param root the repository root, fixing both the destination and the links
    @return the intended path and contents; nothing is written
    """
    rules = _sorted_rules(documents)
    registry = registry_for(root)
    status = statuses_for(rules, root, registry)
    covered = discrimination_covered(root)
    unavailable = sum(
        1
        for r in rules
        if r.force is Force.BINDING
        and status[r.rule_id]
        in {
            VerificationState.UNBUILT,
            VerificationState.UNDECLARED,
        }
    )
    automated = [
        rule
        for rule in rules
        if any(strategy.is_automated for strategy in registry.rules[rule.rule_id].strategies)
    ]
    witnessed = 0 if covered is None else sum(rule.rule_id in covered for rule in automated)
    proxies = sum(
        strategy.relation is DecisionRelation.PROXY
        for evidence in registry.rules.values()
        for strategy in evidence.strategies
    )
    by_module: defaultdict[str, list[Rule]] = defaultdict(list)
    for rule in rules:
        by_module[rule.module_id].append(rule)

    lines = [
        "---",
        "id: meta/INDEX",
        "kind: meta",
        "title: Rule Index",
        "tokens: 0",
        "decay: none",
        "---",
        "",
        GENERATED_BANNER,
        "",
        "# Rule Index",
        "",
        (
            f"{len(rules)} rules across {len(by_module)} modules. "
            "Grep this file for a rule id, then open only the module that owns it."
        ),
        "",
        (
            "**The columns are different claims.** `Force` is the normative obligation. "
            "`Verifier` says what strategy is available, never that it passed. `Relation` "
            "says whether the observable proposition is the rule itself or only a proxy. "
            "`Rejection` records whether the current matrix has watched the rule reject a "
            "counterexample. `Platforms`, `Residual`, and `Field` state where the claim is "
            "supported, what can remain wrong, and what named adopters observed."
        ),
        "",
        (
            "**A proxy cannot decide its parent semantic rule.** Passing its proposition "
            "establishes only the stated syntax or behavior and leaves the printed "
            "residual. `rule-level witnessed` is deliberately weaker than v4's target: "
            "the inherited matrix proves that some strategy rejected a case for that "
            "rule, but cannot yet attribute the rejection to one exact strategy."
        ),
        "",
        (
            f"{unavailable} of {sum(1 for r in rules if r.force is Force.BINDING)} binding "
            "rules lack an available declared strategy. "
            f"{witnessed} of {len(automated)} rules with automated strategies have inherited "
            f"rule-level rejection evidence. {proxies} strategy claims are explicitly proxy "
            "claims. `enforce/ENFORCEMENT.md` expands the complete evidence ledger."
        ),
        "",
    ]

    catalogue = sorted(
        (d for d in documents if d.kind in {Kind.LAW, Kind.FACT, Kind.FRAME, Kind.OPS}),
        key=lambda d: (str(d.kind), d.doc_id),
    )
    if catalogue:
        lines += [
            "## Modules",
            "",
            "| Module | Kind | Tokens | Rules | Load when |",
            "|---|---|---|---|---|",
        ]
        for doc in catalogue:
            keywords = doc.front_matter.get("load_when")
            hint = ", ".join(str(k) for k in keywords[:6]) if isinstance(keywords, list) else ""
            lines.append(
                f"| [{doc.doc_id}]({_link(doc, root)}) | {doc.kind} | "
                f"{doc.front_matter.get('tokens', 0)} | {len(doc.rules)} | {hint} |"
            )
        lines.append("")

    if rules:
        lines += ["## Rules", ""]
        for module_id, module_rules in sorted(by_module.items()):
            lines += [
                f"### {module_id}",
                "",
                _INDEX_RULE_HEADER,
                "|---|---|---|---|---|---|---|---|---|",
            ]
            for rule in module_rules:
                evidence = registry.rules[rule.rule_id]
                lines.append(
                    f"| `{rule.rule_id}` | {rule.force} | "
                    f"{_status_cell(rule, status[rule.rule_id])} | "
                    f"{_relations(evidence)} | {_discrimination(rule, evidence, covered)} | "
                    f"{_platforms(evidence)} | {_residual(evidence)} | "
                    f"{_observations(evidence)} | {rule.title} |"
                )
            lines.append("")

    return Artifact(root / "discipline" / "INDEX.md", "\n".join(lines).rstrip() + "\n")


def _link(doc: Document, root: Path) -> str:
    """A Markdown href to a module, written from where `INDEX.md` will sit.

    @param doc the module to point at
    @param root the repository root
    @return the path relative to `discipline/`, the directory INDEX.md is
        generated into
    @throws ValueError when the module lies outside `discipline/`, which would
        mean it was never part of the corpus this index describes
    """
    return doc.path.relative_to(root / "discipline").as_posix()


def build_rules_json(documents: Sequence[Document], root: Path) -> Artifact:
    """Render `discipline/rules.json`: the same corpus, shaped for a query.

    Carries every field a rule declares, including the ones INDEX.md has no
    column for -- the statement, the reasoning, the supersession -- so that a
    question can be answered without falling back to reading the module. Each
    rule keeps its file and line, which is what makes an answer citable.

    The evidence registry is merged losslessly under each rule. Normative force,
    verifier availability, exact observable propositions, discrimination cases,
    portability, residuals, warrants, observations, and migration remain separate
    fields so a consumer cannot accidentally turn one into a verdict about another.

    @param documents the parsed corpus
    @param root the repository root, for the relative paths in the payload
    @return the intended path and contents; nothing is written
    """
    rules = _sorted_rules(documents)
    registry = registry_for(root)
    observation_registry = observations_for(root)
    status = statuses_for(rules, root, registry)
    payload = {
        "generated_by": "tools/build_index.py",
        "modules": [
            {
                "id": doc.doc_id,
                "kind": str(doc.kind) if doc.kind else None,
                "title": doc.front_matter.get("title"),
                "tokens": doc.front_matter.get("tokens"),
                "load_when": doc.front_matter.get("load_when", []),
                "requires": doc.front_matter.get("requires", []),
                "grounds_on": doc.front_matter.get("grounds_on", []),
                "verified": str(doc.front_matter.get("verified"))
                if doc.front_matter.get("verified")
                else None,
                "decay": doc.front_matter.get("decay"),
                "path": doc.path.relative_to(root).as_posix(),
            }
            for doc in sorted(documents, key=lambda d: d.doc_id)
            if doc.doc_id
        ],
        "field_observations": {
            observation_id: {
                "classification": str(observation.classification),
                "claim": observation.claim,
                "evidence_kind": str(observation.evidence_kind),
                "observed_in": list(observation.observed_in),
                "reproduction": observation.reproduction,
                "scope": observation.scope,
                "source": observation.source,
            }
            for observation_id, observation in sorted(observation_registry.observations.items())
        },
        "rules": [
            _rule_payload(rule, registry.rules[rule.rule_id], status[rule.rule_id], root)
            for rule in rules
        ],
    }
    return Artifact(
        root / "discipline" / "rules.json",
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
    )


def _rule_payload(
    rule: Rule,
    evidence: RuleEvidence,
    state: VerificationState,
    root: Path,
) -> dict[str, object]:
    """Merge one normative rule and its complete evidence record.

    @param rule normative Markdown record
    @param evidence authored epistemic and verification claims for the same id
    @param state verifier availability measured against this repository
    @param root repository root used to make the source path relative
    @return JSON-shaped record without collapsing distinct claims
    """
    return {
        "id": rule.rule_id,
        "module": rule.module_id,
        "title": rule.title,
        "force": str(rule.force),
        "mechanisms": list(rule.mechanisms),
        "statement": rule.statement,
        "why": rule.why,
        "check": rule.check,
        "no_mechanism": rule.no_mechanism,
        "see": list(rule.see),
        "superseded_by": rule.superseded_by,
        "path": rule.path.relative_to(root).as_posix(),
        "line": rule.line,
        "applicability": {
            "units": [str(unit) for unit in evidence.units],
            "capabilities": list(evidence.capabilities),
        },
        "failure_mode": evidence.failure_mode,
        "warrants": [
            {
                "source": warrant.source,
                "relation": str(warrant.relation),
                "confidence": str(warrant.confidence),
            }
            for warrant in evidence.warrants
        ],
        "verification": {
            "state": str(state),
            "strategies": [
                {
                    "mechanism": strategy.mechanism,
                    "kind": str(strategy.kind),
                    "relation": str(strategy.relation),
                    "proposition": strategy.proposition,
                    "residual": strategy.residual,
                    "must_pass": strategy.must_pass,
                    "must_reject": strategy.must_reject,
                    "platforms": list(strategy.platforms),
                    "not_applicable": strategy.not_applicable,
                }
                for strategy in evidence.strategies
            ],
        },
        "field_observations": list(evidence.observations),
        "migration": {
            "source": evidence.migration.source,
            "disposition": str(evidence.migration.disposition),
            "guidance": evidence.migration.guidance,
        },
    }


def _evidence_census(
    rules: Sequence[Rule],
    root: Path,
    registry: EvidenceRegistry,
    states: dict[str, VerificationState],
    covered: frozenset[str] | None,
) -> EvidenceCensus:
    """Compute summary values once without obscuring the renderer.

    @param rules sorted normative corpus
    @param root repository against which local mechanisms resolve
    @param registry evidence records joined to the rules
    @param states verifier availability by stable rule id
    @param covered rule-level mutations inherited from the v3 matrix
    @return all counts and subsets shown in the generated ledger
    """
    binding = tuple(rule for rule in rules if rule.force is Force.BINDING)
    named = frozenset(mechanism for rule in rules for mechanism in rule.mechanisms)
    pending = tuple(
        sorted(
            mechanism for mechanism in named if mechanism_is_implemented(mechanism, root) is False
        )
    )
    strategies = tuple(
        strategy for evidence in registry.rules.values() for strategy in evidence.strategies
    )
    automated = tuple(
        rule
        for rule in rules
        if any(strategy.is_automated for strategy in registry.rules[rule.rule_id].strategies)
    )
    proxy_count = sum(strategy.relation is DecisionRelation.PROXY for strategy in strategies)
    return EvidenceCensus(
        binding=binding,
        advisory=tuple(rule for rule in rules if rule.force is Force.ADVISORY),
        open_rules=tuple(rule for rule in rules if rule.force is Force.OPEN),
        named_mechanisms=named,
        pending_mechanisms=pending,
        unavailable=tuple(
            rule
            for rule in binding
            if states[rule.rule_id] in {VerificationState.UNBUILT, VerificationState.UNDECLARED}
        ),
        state_counts=Counter(str(states[rule.rule_id]) for rule in rules),
        strategy_count=len(strategies),
        direct_count=len(strategies) - proxy_count,
        proxy_count=proxy_count,
        automated_rule_count=len(automated),
        witnessed_rule_count=(
            0 if covered is None else sum(rule.rule_id in covered for rule in automated)
        ),
        observed_rule_count=sum(
            bool(evidence.observations) for evidence in registry.rules.values()
        ),
    )


def build_enforcement(documents: Sequence[Document], root: Path) -> Artifact:
    """Render the complete rule-evidence census for human review.

    The historical filename remains part of the package API, but its v4 contents
    no longer flatten mechanism presence into semantic assurance. The ledger
    separates force, verifier availability, direct/proxy relation, inherited
    rule-level rejection evidence, platform support, field observations, and the
    residual left by each strategy.

    @param documents the parsed corpus
    @param root the repository root, fixing the destination and locating mechanisms
    @return the intended path and contents; nothing is written
    """
    rules = _sorted_rules(documents)
    registry = registry_for(root)
    status = statuses_for(rules, root, registry)
    covered = discrimination_covered(root)
    census = _evidence_census(rules, root, registry, status, covered)

    lines = [
        GENERATED_BANNER,
        "",
        "# Verification Evidence",
        "",
        (
            "This ledger keeps unlike claims unlike. A rule can be normatively binding while "
            "its verifier is absent; a verifier can exist while deciding only a proxy; a "
            "proxy can pass while its residual remains true; and a successful adopter does "
            "not prove universal benefit. No state below is a project-gate outcome."
        ),
        "",
        (
            f"- **{len(census.binding)}** binding rules; "
            f"**{len(census.unavailable)}** lack an available "
            "declared strategy."
        ),
        (
            f"- **{len(census.advisory)}** advisory rules and "
            f"**{len(census.open_rules)}** open rules."
        ),
        (
            f"- **{census.strategy_count}** exact strategy records: "
            f"**{census.direct_count}** direct and **{census.proxy_count}** proxy claims."
        ),
        (
            f"- **{census.witnessed_rule_count}/{census.automated_rule_count}** rules "
            "with automated strategies have "
            "inherited rule-level rejection evidence; v4 still owes strategy-level attribution."
        ),
        f"- **{census.observed_rule_count}/{len(rules)}** rules carry named field observations.",
        (
            f"- **{len(census.named_mechanisms) - len(census.pending_mechanisms)}/"
            f"{len(census.named_mechanisms)}** named mechanisms resolve locally or delegate "
            f"explicitly; **{len(census.pending_mechanisms)}** local mechanisms are absent."
        ),
        "",
        "## Verifier-state census",
        "",
        (
            "Measured against this tree, not copied from the rule heading. "
            "`discipline/rules.json` carries the same value under `verification.state`, and "
            "`discipline/INDEX.md` shows it in the `Verifier` column."
        ),
        "",
        "| State | Rules | Means |",
        "|---|---|---|",
        (
            f"| `local-verifier` | {census.state_counts['local-verifier']} | "
            "repository-local code observes every strategy |"
        ),
        (
            f"| `external-verifier` | {census.state_counts['external-verifier']} | "
            "every strategy delegates to a configured tool |"
        ),
        (
            f"| `mixed-verifiers` | {census.state_counts['mixed-verifiers']} | "
            "several verifier kinds contribute |"
        ),
        (
            f"| `structured-review` | {census.state_counts['structured-review']} | "
            "judgment is recorded in a checked review artifact |"
        ),
        (
            f"| `unbuilt` | {census.state_counts['unbuilt']} | "
            "at least one named local verifier is absent |"
        ),
        (
            f"| `undeclared` | {census.state_counts['undeclared']} | "
            "the active rule has no strategy record |"
        ),
        (
            f"| `retired` | {census.state_counts['retired']} | "
            "the stable id remains only for history |"
        ),
        "",
    ]

    lines += _external_tool_section()

    if census.unavailable:
        lines += [
            "## Binding rules without an available strategy",
            "",
            (
                "These remain normative obligations, but the declared verifier is absent or "
                "missing. They cannot contribute to a green release verdict."
            ),
            "",
            "| Rule | Verifier | Mechanism | Title |",
            "|---|---|---|---|",
        ]
        for rule in census.unavailable:
            mechanisms = " ".join(f"`{m}`" for m in rule.mechanisms) or "—"
            lines.append(
                f"| `{rule.rule_id}` | `{status[rule.rule_id]}` | {mechanisms} | {rule.title} |"
            )
        lines.append("")

    if census.pending_mechanisms:
        lines += [
            (
                "> **Mechanisms still to build.** Listed rather than assumed closed: a rule "
                "whose verifier does not exist cannot report a violation. `tools/validate.py` "
                "reports each absent declaration as `V080`."
            ),
            "",
            "| Mechanism | Rules |",
            "|---|---|",
        ]
        for mechanism in census.pending_mechanisms:
            owners = ", ".join(f"`{r.rule_id}`" for r in rules if mechanism in r.mechanisms)
            lines.append(f"| `{mechanism}` | {owners} |")
        lines.append("")

    if rules:
        lines += [
            "## Rule evidence",
            "",
            _LEDGER_RULE_HEADER,
            "|---|---|---|---|---|---|---|---|---|",
        ]
        for rule in rules:
            evidence = registry.rules[rule.rule_id]
            lines.append(
                f"| `{rule.rule_id}` | {rule.force} | "
                f"{_status_cell(rule, status[rule.rule_id])} | {_relations(evidence)} | "
                f"{_discrimination(rule, evidence, covered)} | {_platforms(evidence)} | "
                f"{_observations(evidence)} | {_residual(evidence, limit=180)} | "
                f"{rule.title} |"
            )
        lines.append("")

        counts = Counter(m.split(":", 1)[0] for r in rules for m in r.mechanisms)
        lines += ["### Mechanisms in use", "", "| Kind | Rules |", "|---|---|"]
        lines += [f"| `{kind}` | {n} |" for kind, n in sorted(counts.items())]
        lines.append("")

    if census.advisory:
        lines += [
            "## Advisory rationale",
            "",
            (
                "Each advisory rule records why its semantic conclusion is not reduced to an "
                "automated proposition. That reason is review input, not a waiver."
            ),
            "",
            "| Rule | Why no mechanism exists | Title |",
            "|---|---|---|",
        ]
        for rule in census.advisory:
            lines.append(
                f"| `{rule.rule_id}` | {rule.no_mechanism or '**unjustified**'} | {rule.title} |"
            )
        lines.append("")

    if census.open_rules:
        lines += [
            "## Blocked on an open decision",
            "",
            "| Rule | Title |",
            "|---|---|",
        ]
        lines += [f"| `{r.rule_id}` | {r.title} |" for r in census.open_rules]
        lines.append("")

    return Artifact(root / "enforce" / "ENFORCEMENT.md", "\n".join(lines).rstrip() + "\n")


def main(argv: Sequence[str] | None = None) -> int:
    """Regenerate every derived artifact, or under `--check` only report staleness.

    Rewriting the token counts changes the very files the artifacts describe, so
    the corpus is parsed a second time whenever a count actually moved, and the
    artifacts then carry the new numbers rather than the ones measured before the
    pass. Under `--check` nothing is rewritten, so nothing is re-read.

    @param argv command-line arguments, defaulting to `sys.argv`
    @return 0 on success, 1 when `--check` finds anything out of date
    """
    # The console encoding is not ours to choose, and a tool that dies on one is
    # worse than one that renders a character imperfectly.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser(description="Regenerate derived corpus artifacts.")
    parser.add_argument("--check", action="store_true", help="report staleness, write nothing")
    parser.add_argument("--root", type=Path, default=REPO_ROOT, help="repository root")
    args = parser.parse_args(argv)
    root = args.root.resolve()

    documents = load(root)
    stale_tokens = refresh_tokens(documents, write=not args.check)
    if stale_tokens and not args.check:
        documents = load(root)  # re-read so the artifacts carry the new counts

    artifacts = [
        build_index(documents, root),
        build_rules_json(documents, root),
        build_enforcement(documents, root),
    ]
    stale = [a for a in artifacts if a.is_stale()]

    if args.check:
        for path in stale_tokens:
            print(f"stale tokens: {path.relative_to(root).as_posix()}")
        for artifact in stale:
            print(f"stale artifact: {artifact.path.relative_to(root).as_posix()}")
        total = len(stale_tokens) + len(stale)
        print(f"{total} stale file(s)." if total else "up to date.")
        return 1 if total else 0

    for artifact in artifacts:
        artifact.write()
    rules = sum(len(d.rules) for d in documents)
    print(
        f"wrote {len(artifacts)} artifact(s); {len(documents)} modules, {rules} rules, "
        f"{len(stale_tokens)} token count(s) refreshed."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
